# Generated by Django 5.0 on 2024-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Authencation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="documents",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
