# Generated by Django 5.0.1 on 2024-01-30 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Authencation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_org",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
    ]
