# Generated by Django 5.0.1 on 2024-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Authencation",
            "0002_remove_customuser_is_active_remove_customuser_is_org_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_org",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
