# Generated by Django 5.0.1 on 2024-01-18 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Recipient", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=10)),
                ("description", models.TextField(default="", max_length=1000)),
                ("criteria", models.CharField(default="", max_length=10)),
                ("image_url", models.ImageField(default="", upload_to="images")),
                ("date_created", models.DateField(default=django.utils.timezone.now)),
                ("expiration_durations", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Badge_Assignments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_verification_code",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "recipient_id",
                    models.ManyToManyField(
                        related_name="recipient_id", to="Recipient.recipients"
                    ),
                ),
                (
                    "badge_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_id",
                        to="Organisation.badges",
                    ),
                ),
            ],
        ),
    ]
