# Generated by Django 5.0.1 on 2024-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Organisation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badges",
            name="image_url",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images"
            ),
        ),
    ]
