# Generated by Django 5.0.1 on 2024-01-22 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Organisation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badges",
            name="date_created",
            field=models.DateField(
                blank=True, default=datetime.date(2024, 1, 22), null=True
            ),
        ),
    ]
