<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-23 11:56
=======
# Generated by Django 5.0.1 on 2024-01-23 12:04
>>>>>>> c0e49230fb7fdba44a035c215066d2264fa2fd36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=10)),
                ("email", models.EmailField(default="", max_length=50)),
            ],
        ),
    ]
